require: rubocop-rails

AllCops:
  Exclude:
    - 'bin/bundle'

Style/Documentation:
  Exclude:
    - 'spec/**/*'
    - 'test/**/*'
    - 'app/controllers/users_controller.rb'
    - 'app/helpers/application_helper.rb'
    - 'app/helpers/users_helper.rb'
    - 'config/application.rb'
    - 'db/migrate/20221010093031_create_users.rb'

Style/IfUnlessModifier:
  Exclude:
    - 'bin/bundle'
Metrics/BlockLength:
  Max: 47
Metrics/CyclomaticComplexity:
  Max: 9
Metrics/MethodLength:
  Max: 12
Metrics/PerceivedComplexity:
  Max: 9
Layout/LineLength:
  Max: 198





